let products=[],settings={},selectedCategory='Semua',selectedLabel='',sortMode='default',wishlist=new Set(JSON.parse(localStorage.getItem('baylos_wishlist')||'[]')),db=null,sessionId=null,heroIndex=0,heroTimer=null,currentProduct=null;
const cfg=window.BAYLOS_CONFIG||{};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const rupiah=v=>v==null||v===''?'Harga belum diatur':'Rp '+Number(v).toLocaleString('id-ID');
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function safeUrl(v){try{const u=new URL(String(v||''),location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}}
function session(){let s=localStorage.getItem('baylos_session_id');if(!s){s=crypto.randomUUID?crypto.randomUUID():'b-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem('baylos_session_id',s)}return s}
function source(){const p=new URLSearchParams(location.search);if(p.get('utm_source'))return p.get('utm_source');if(!document.referrer)return'Langsung';try{const h=new URL(document.referrer).hostname.toLowerCase();for(const x of ['google','tiktok','instagram','facebook','youtube','whatsapp'])if(h.includes(x))return x[0].toUpperCase()+x.slice(1);return h}catch{return'Lainnya'}}
function device(){return innerWidth<=600?'Mobile':innerWidth<=1024?'Tablet':'Desktop'}
async function analytics(type,p={}){if(!db||!sessionId)return;const payload={session_id:sessionId,event_type:type,product_id:/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(p.id||''))?p.id:null,product_name:p.name||null,page:location.pathname,source:source(),referrer:document.referrer||null,device:device()};try{await db.from('analytics_events').insert(payload)}catch(e){console.warn('Analytics:',e.message)}}
function imageList(p){let a=[];try{a=Array.isArray(p.image_urls)?p.image_urls:(typeof p.image_urls==='string'?JSON.parse(p.image_urls||'[]'):[])}catch{};if(!Array.isArray(a))a=[];if(p.image_url&&!a.includes(p.image_url))a.unshift(p.image_url);return a.filter(Boolean).slice(0,4)}
function allSettings(){return {...{hero_image_url:'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1600&q=85',hero_label:'BAYLOS SHOPPING MURAH',hero_title:'Pilihan cantik.\nHarga bersahabat.',hero_description:'Temukan produk pilihan Baylos dengan tampilan belanja yang lebih nyaman.'},...settings}}
function renderHero(){const s=allSettings();const imgs=[s.hero_image_url,s.hero_image_url,s.hero_image_url].filter(Boolean);$('heroTrack').innerHTML=imgs.map((im,i)=>`<article class="hero-slide" style="background-image:url('${esc(im)}')"><div class="hero-content"><span class="eyebrow">${esc(s.hero_label)}</span><h1>${esc(s.hero_title).replace(/\\n/g,'<br>')}</h1><p>${esc(s.hero_description)}</p><a class="hero-btn" href="#productsSection">Belanja sekarang →</a></div></article>`).join('');$('heroDots').innerHTML=imgs.map((_,i)=>`<button class="${i===0?'active':''}" data-hero="${i}"></button>`).join('');heroGo(0);clearInterval(heroTimer);heroTimer=setInterval(()=>heroMove(1),5500)}
function heroGo(i){heroIndex=(i+3)%3;$('heroTrack').style.transform=`translateX(-${heroIndex*33.333333}%)`;document.querySelectorAll('[data-hero]').forEach((b,n)=>b.classList.toggle('active',n===heroIndex))}
function heroMove(n){heroGo(heroIndex+n)}
function categories(){return [...new Set(products.map(p=>p.category).filter(Boolean))]}
function renderCategories(){const cats=categories();$('categoryRow').innerHTML=[['Semua',products.length],...cats.map(c=>[c,products.filter(p=>p.category===c).length])].map(([c,n])=>`<button class="category-btn ${selectedCategory===c?'active':''}" data-cat="${esc(c)}"><strong>${esc(c)}</strong><span>${n} produk</span></button>`).join('');$('categoryFilter').innerHTML='<option value="Semua">Semua kategori</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('categoryFilter').value=selectedCategory}
function filtered(){let q=($('searchInput').value||'').toLowerCase().trim();let a=products.filter(p=>(selectedCategory==='Semua'||p.category===selectedCategory)&&(selectedLabel===''||String(p.label||'').toUpperCase().trim()===selectedLabel)&&(!q||`${p.name||''} ${p.category||''} ${p.description||''}`.toLowerCase().includes(q))&&(!wishlistMode||wishlist.has(String(p.id))));if(sortMode==='price-low')a.sort((x,y)=>(+x.price||0)-(+y.price||0));if(sortMode==='price-high')a.sort((x,y)=>(+y.price||0)-(+x.price||0));if(sortMode==='newest')a.sort((x,y)=>new Date(y.created_at||0)-new Date(x.created_at||0));if(sortMode==='name')a.sort((x,y)=>String(x.name).localeCompare(String(y.name),'id'));return a}
let wishlistMode=false;
function card(p){const imgs=imageList(p),w=wishlist.has(String(p.id));return `<article class="product-card" data-product-id="${esc(p.id)}"><div class="product-image"><img src="${esc(imgs[0]||'https://placehold.co/800x800?text=Baylos')}" alt="${esc(p.name)}" loading="lazy"><span class="label">${p.label?esc(p.label):'BAYLOS'}</span><button class="wish ${w?'active':''}" data-wish="${esc(p.id)}">${w?'♥':'♡'}</button></div><div class="product-info"><small>${esc(p.category||'Produk')}</small><div class="product-name">${esc(p.name||'Produk Baylos')}</div><div class="product-price">${rupiah(p.price)}</div><div class="product-actions"><button class="detail-btn" data-detail="${esc(p.id)}">Detail</button><a class="buy-btn" data-buy="${esc(p.id)}" href="${esc(safeUrl(p.affiliate_url)||'#')}" target="_blank" rel="noopener noreferrer sponsored nofollow">🛒 Beli</a></div></div></article>`}
function renderProducts(){const a=filtered();$('productCount').textContent=`${a.length} produk`;$('productGrid').innerHTML=a.length?a.map(card).join(''):'<div style="grid-column:1/-1;padding:45px;text-align:center;color:#747b89">Produk tidak ditemukan.</div>';document.querySelectorAll('[data-product-id]').forEach(el=>{if(!el.__obs){el.__obs=1;analytics('product_impression',{id:el.dataset.productId,name:products.find(p=>String(p.id)===el.dataset.productId)?.name})}})}
function rail(label,id){const items=products.filter(p=>String(p.label||'').toUpperCase().trim()===label);const section=$(id).closest('.showcase-section');if(!items.length){section.style.display='none';return}section.style.display='block';$(id).innerHTML=items.slice(0,12).map(p=>`<article class="rail-card"><img src="${esc(imageList(p)[0]||'https://placehold.co/800x800?text=Baylos')}" alt="${esc(p.name)}" loading="lazy"><div class="rail-info"><small>${esc(p.category||'Produk')}</small><strong>${esc(p.name)}</strong><b>${rupiah(p.price)}</b><a class="rail-buy" data-buy="${esc(p.id)}" href="${esc(safeUrl(p.affiliate_url)||'#')}" target="_blank" rel="noopener noreferrer sponsored nofollow">Beli sekarang</a></div></article>`).join('')}
function renderRails(){rail('PROMO','promoRail');rail('BEST SELLER','bestRail');rail('TERBARU','latestRail')}
function openProduct(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;currentProduct=p;const imgs=imageList(p);$('modalCategory').textContent=p.category||'PRODUK';$('modalName').textContent=p.name||'Produk Baylos';$('modalPrice').textContent=rupiah(p.price);$('modalDescription').textContent=p.description||'Produk pilihan Baylos.';$('modalMainImage').src=imgs[0]||'https://placehold.co/800x800?text=Baylos';$('modalMainImage').alt=p.name||'Produk';$('modalThumbs').innerHTML=imgs.map((im,i)=>`<button class="${i===0?'active':''}" data-thumb="${i}"><img src="${esc(im)}" alt=""></button>`).join('');$('modalWishlist').textContent=wishlist.has(String(p.id))?'♥ Hapus Wishlist':'♡ Wishlist';$('modalBuy').href=safeUrl(p.affiliate_url)||'#';$('productModal').classList.add('open');$('productModal').setAttribute('aria-hidden','false');analytics('product_detail_view',p)}
function closeProduct(){ $('productModal').classList.remove('open');$('productModal').setAttribute('aria-hidden','true') }
function toggleWish(id){id=String(id);if(wishlist.has(id))wishlist.delete(id);else wishlist.add(id);localStorage.setItem('baylos_wishlist',JSON.stringify([...wishlist]));$('wishlistCount').textContent=wishlist.size;renderProducts();if(currentProduct&&String(currentProduct.id)===id)$('modalWishlist').textContent=wishlist.has(id)?'♥ Hapus Wishlist':'♡ Wishlist';toast(wishlist.has(id)?'Disimpan ke Wishlist':'Dihapus dari Wishlist')}
function buy(id,e){const p=products.find(x=>String(x.id)===String(id));if(!p||!safeUrl(p.affiliate_url)){e.preventDefault();toast('Link pembelian belum tersedia.');return false}analytics('affiliate_click',p);return true}
async function load(){if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY){toast('Koneksi toko belum tersedia.');return}db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);sessionId=session();analytics('page_view');const [pr,sr]=await Promise.all([db.from('products').select('*').eq('is_active',true).order('sort_order',{ascending:true}).order('created_at',{ascending:false}),db.from('store_settings').select('*').eq('id',1).maybeSingle()]);if(pr.error)console.warn(pr.error);products=pr.data||[];settings=sr.data||{};renderHero();renderCategories();renderRails();renderProducts()}
function searchOpen(){ $('searchWrap').classList.add('open');$('searchInput').focus() }
$('menuBtn').onclick=()=>{$('drawer').classList.add('open');$('drawerBackdrop').classList.add('open')};$('closeDrawer').onclick=()=>{$('drawer').classList.remove('open');$('drawerBackdrop').classList.remove('open')};$('drawerBackdrop').onclick=()=>{$('drawer').classList.remove('open');$('drawerBackdrop').classList.remove('open')};$('searchBtn').onclick=searchOpen;$('clearSearch').onclick=()=>{$('searchInput').value='';selectedLabel='';renderProducts()};$('searchInput').oninput=()=>{selectedLabel='';renderProducts()};$('sortSelect').onchange=e=>{sortMode=e.target.value;renderProducts()};$('categoryFilter').onchange=e=>{selectedCategory=e.target.value;renderCategories();renderProducts();};$('heroPrev').onclick=()=>heroMove(-1);$('heroNext').onclick=()=>heroMove(1);$('heroDots').onclick=e=>{if(e.target.dataset.hero)heroGo(+e.target.dataset.hero)};$('categoryRow').onclick=e=>{const b=e.target.closest('[data-cat]');if(b){selectedCategory=b.dataset.cat;selectedLabel='';renderCategories();renderProducts();$('productsSection').scrollIntoView({behavior:'smooth'})}};document.addEventListener('click',e=>{const d=e.target.closest('[data-detail]');if(d)openProduct(d.dataset.detail);const w=e.target.closest('[data-wish]');if(w){e.stopPropagation();toggleWish(w.dataset.wish)}const b=e.target.closest('[data-buy]');if(b)buy(b.dataset.buy,e);const t=e.target.closest('[data-label]');if(t){selectedLabel=t.dataset.label;selectedCategory='Semua';renderCategories();renderProducts();$('productsSection').scrollIntoView({behavior:'smooth'})}const th=e.target.closest('[data-thumb]');if(th&&currentProduct){const imgs=imageList(currentProduct),i=+th.dataset.thumb;$('modalMainImage').src=imgs[i];document.querySelectorAll('[data-thumb]').forEach(x=>x.classList.remove('active'));th.classList.add('active')}});document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=closeProduct);$('modalWishlist').onclick=()=>currentProduct&&toggleWish(currentProduct.id);$('modalBuy').onclick=e=>currentProduct&&buy(currentProduct.id,e);$('wishlistBtn').onclick=()=>{wishlistMode=!wishlistMode;selectedLabel='';selectedCategory='Semua';renderCategories();renderProducts();$('productsSection').scrollIntoView({behavior:'smooth'})};document.querySelectorAll('[data-bottom]').forEach(b=>b.onclick=()=>{const x=b.dataset.bottom;if(x==='home')scrollTo(0,0);if(x==='categories')$('categories').scrollIntoView({behavior:'smooth'});if(x==='search')searchOpen();if(x==='wishlist')$('wishlistBtn').click()});document.querySelectorAll('[href^="#"]').forEach(a=>a.addEventListener('click',()=>{$('drawer').classList.remove('open');$('drawerBackdrop').classList.remove('open')}));$('wishlistCount').textContent=wishlist.size;$('year').textContent=new Date().getFullYear();load();
